### ISSUE TITLE
Academic Use Agreement is unavailable

### ISSUE THREAD

**Issue by abnova** [blackducksw/ohloh_api#23]
Hello!

Based on the following page (http://meta.ohloh.net/faqs/can-i-use-ohloh-data-for-academic-research), in addition to Terms of Use, academic researchers, who would like to use Ohloh APIs, need to accept a special Academic Use Agreement. However, unfortunately, such agreement is still not available (http://meta.ohloh.net/academic-use-agreement). It would be great, if you could provide it at your earliest convenience. In the meantime, please provide an estimated time frame for publishing this document.

In addition, two relevant questions:

Do graduate students doing research on open source as part of their thesis or dissertation, still need to use the Academic Use Agreement, or it's meant only for professional academic researchers?

What open source repositories does Ohloh cover? (Frankly, I'm very disappointed in how Black Duck and Ohloh treated me. Don't get me wrong, I like what you do and I'm sure you're smart and nice people, but... I sent this question in November(!) and was told that you will get back to me soon. I understand that you're busy, but still think that four months is not "soon" by any standards.)

I can definitely do my research without Ohloh data and am already prepared to do just that, but decided to get in touch and try one more time... I thought that using your (open) data not only could be useful for my dissertation research, but it could give an additional positive exposure for your data, APIs, service and parent company in open source and information systems (IS) research circles.

I look forward to hearing from you soon.

Sincerely,
Aleksandr Blekh
Ph.D. Candidate (IS)

**Comment by jcrben** [comment]
fyi, the academic agreement seems to be available now, i.e. those links work. this issue should be closed.

**Comment by abnova** [comment]
@jcrben Thank you for letting me know. It's too late. Plus, fortunately, I'm done with my dissertation and without using Ohloh's data. I'm amazed about how unresponsive they were to my cooperation requests. I'm amazed (in a negative sense) by their ignorance and disrespect. Naturally, there will be no respect from me toward that division and its parent company.

**Comment by PeterDP** [comment]
Hello @abnova; I wish to apologize for the lack of response you received to your request. Although any excuse is poor, your request simply fell through the cracks.  We are a small team trying to maintain analysis on over half a million code repositories on an aging code base and infrastructure.  We have been completely focused on maintaining site performance as we re-engineer the code and infrastructure to keep the service available to the open source community.  Fortunately, the results of our work will soon be put into production and we will be able to return to developing new features and being more responsive to our user base.  You are of course correct to have felt ignored and I offer my personal apologies as the technical team lead.  We will strive to do better in the future.  Sincerely yours, pdp.

**Comment by abnova** [comment]
@PeterDP Apology accepted. I guess, it is never too late for good things to happen. I look forward to seeing your platform feature-rich and open, especially since FLOSS ecosystem continues to remain among of my main research and professional interests. Feel free to connect with me on professional social networks. Best regards, Alex.
